London - Class 7 - Tanika - Javascript Core 1 - Week 2
CodeYourFuture/JavaScript-Core-1-Coursework-Week2 pull request #42
Opened 2021-01-28 00:40 UTC by Trobinsonshoots

I have completed all the exercises. 

On the extra exercise there was an issue getting the final function working. It states that the helper function is called 'isRadioFrequency' but there wasn't a function with that name. The correct function was 'getAvailableStations' i'm not sure if this was part of the challenge, but I changed the task instructions to state the correct function name hope that was alright.

Details

Name: Tanika
City: London
Slack Name: Tanika Robinson

# Homework Details

Module: Javascript Core 1
Week: 2

2021-01-28 14:19 UTC, iTrip23 requested changes
Hi Tanika,
You have done a great job with the homework, all your code is working, I suggested some minor changes. Hope they help you understand the code better.
Happy coding!

2021-01-28 14:19 UTC, iTrip23 commented on exercises/C-comparison-operators/exercise.js
> +var moreStudentsThanMentors = true; // finish this statement
Hi Tanika,
I have done the exact same thing at first, hardcoded the answers.
```suggestion
var moreStudentsThanMentors = studentCount > mentorCount;
```
You can try and do the same for the rest of the file.
Thanks

2021-01-28 14:19 UTC, iTrip23 commented on exercises/D-predicates/exercise.js
> +  if (number > 0 && number < 10){
Something to keep in mind is that this statement: `number > 0 && number < 10` is going to return a boolean value(true or false), and you can shorten your code by writing something like:
```suggestion
  function isBetweenZeroAnd10(number) {
  return number > 0 && number < 10;
  }
```
This is just something to keep in mind when writing code. 
Hope this helps.

2021-01-28 14:19 UTC, iTrip23 commented on exercises/F-logical-operators/exercise2.js
> +  if (num < 0) {
The same principle applies here with the statements in this folder:
`return num < 0;`

2021-01-28 20:31 UTC, Laura-TM commented on mandatory/2-function-creation.js
> +    arr[i] = parseFloat(arr[i].toFixed(2)) +"%";
I like the use of parseFloat, this is something I need to learn more about.

2021-01-28 20:32 UTC, Laura-TM commented
Left some feedback for you, overall, well organised and use of advanced features.

2021-01-29 14:57 UTC, ChrisOwen101 commented on extra/1-radio-stations.js
> + * - There is a helper function called  'getAvailableStations' that takes an integer as an argument and returns a boolean.
Thanks for spotting Laura and Tanika! I've now updated this coursework. :)

2021-05-14 02:01 UTC, closed without merging