Alexander Msumba_ South Africa_ javascript_ core _1_ week 2
CodeYourFuture/JavaScript-Core-1-Coursework-Week2 pull request #62
Opened 2021-01-29 21:05 UTC by MSUMBA-art

# Your Details

- Your Name: Alexander
- Your City: Cape Town- South Africa
- Your Slack Name: Alexander Msumba

# Homework Detailsk

- Module:  JavaScript-Core-1
- Week: 2

2021-01-29 22:16 UTC, SerialCarKey requested changes
Hi Alexander, Once again . super clean code .

i've just noticed some small things to review on the Mandatory exercises

There are slight Syntax errors within the Fix-Functions.JS & the Function-Creation .
 
such as the Identifier 'sortedLetters' has already been declared syntax error within Fix-Functions.

Other than that, Great Work :D

2021-03-28 22:38 UTC, he-man-david commented on exercises/D-predicates/exercise.js
> +  return typeof number === "value";
what is typeof number here and what is question asking?

2021-03-28 22:39 UTC, he-man-david commented on exercises/E-conditionals/exercise.js
> +if (name) {
how can we compare to see if daniel is mentor?

2021-03-28 22:39 UTC, he-man-david commented on exercises/G-conditionals-2/exercise-1.js
> +    } else if (number >= 0){
do we need else if?

2021-03-28 22:40 UTC, he-man-david commented on exercises/G-conditionals-2/exercise-2.js
> +  }else if(grade => 50) {
do we need 3 conditions here?

2021-03-28 22:40 UTC, he-man-david commented on exercises/G-conditionals-2/exercise-3.js
> +  if (mark >= 80) {
great job!

2021-03-28 22:40 UTC, he-man-david commented on mandatory/1-fix-functions.js
> +  return "I am not happy";
will this line ever execute?

2021-03-28 22:42 UTC, he-man-david commented on mandatory/2-function-creation.js
> +  strArr[i] = strArr[i].toLowerCase();
can we reduce calling strArr[i] so many times?

2021-03-28 22:44 UTC, he-man-david commented on mandatory/2-function-creation.js
>    return; // complete this statement
are we actually returning anything here?

2021-03-28 22:45 UTC, he-man-david commented on mandatory/2-function-creation.js
> +  for (let i=0; i<arr.length; i++){
we can also do this let newArr = [...arr]; Can we do this without creating a new array? Try using a filter! https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2021-03-29 09:12 UTC, MSUMBA-art commented
Thanks, will go through again

On Mon., 29 Mar. 2021, 00:45 David He, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In mandatory/2-function-creation.js
> <https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week2/pull/62#discussion_r602944379>
> :
>
> >
>  /*
>  Write a function that returns a copy of the given array arr, but with the element at the given index, index removed.
>  The function must NOT change the original array, arr.
>  */
>
>  function remove(arr, index) {
> +  let newArr = [];
> +  for (let i=0; i<arr.length; i++){
>
> we can also do this let newArr = [...arr]; Can we do this without creating
> a new array? Try using a filter!
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week2/pull/62#pullrequestreview-622792063>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQBIJP3VZ2UJTS5LDFJZW5DTF6WRZANCNFSM4WZREY2A>
> .
>

2021-05-14 02:00 UTC, closed without merging