NorthWest - Class 4 - Anza Azam -Javascript Module Core 1 -Week 2
CodeYourFuture/JavaScript-Core-1-Coursework-Week2 pull request #91
Opened 2021-06-28 21:15 UTC by Anza-Azam

**Volunteers: Are you marking this coursework?** _You can find a guide on how to mark this coursework in `HOW_TO_MARK.md` in the root of this repository_

# Your Details

- Your Name: Anza Azam
- Your City: North west
- Your Slack Name:Anza-Azam

# Homework Details

- Module: JS Core1
- Week: week 2

# Notes

- What did you find easy?
pseudo code function modelling
- What did you find hard?
finding builtin methods
- What do you still not understand?

- Any other notes?

2021-06-29 10:57 UTC, erin-switchstitch reviewed
I really liked your use of both the lower case 'd' and the uppercase 'D' for exercise 2 !

2021-06-29 11:04 UTC, erin-switchstitch reviewed
Exercises G-conditionals - exercise 3 :
Not particularly important but you may be able to reduce the amount of code in your 'else if' statements. If you set them out in the right order (which you have) you would not need to say 
"  else if (mark < 80 && mark > 60) "       only      "else if (mark >= 60) "


function calculateGrade(mark) {
  if (mark >= 80) {
    return "A";
  } else if (mark >= 60) {
    return "B"
  } else if (mark >= 50) {
    return "C";
  } else {
    return "F";
  }}

2021-06-29 11:12 UTC, erin-switchstitch reviewed
I've gone through and checked all of your exercises (B to J) and as far as I can see everything there is correct - I've left a couple of comments about some very slight tweaks you may want to make. Well done, really good job :) !!!!

2021-06-30 13:37 UTC, konikalily commented on extra/1-radio-stations.js
> +}
Hi Anza, just a thought : could you consider using .push() here instead of frequencies[i - 87] = i ? Otherwise your code is very good. Thank you.

2021-06-30 13:38 UTC, konikalily requested changes
Hi Anza, just a thought : could you consider using .push() here instead of frequencies[i - 87] = i ? Otherwise your code is very good. Thank you.

2021-07-01 17:13 UTC, KarenPudner commented on extra/1-radio-stations.js
> +	for (let i = 87; i < 109; i++) {
Maybe assign 87 and 109 to variables called something like startFrequency and endFrequency to make the code more understandable

2021-07-01 17:14 UTC, KarenPudner commented on extra/1-radio-stations.js
> +	let frequency= getAllFrequencies();
This shouldn't be indented - it should be the same indentation as `let station = [];`

2021-07-01 17:25 UTC, KarenPudner commented on extra/1-radio-stations.js
> +		if (isRadioStation(frequency[i])) {
Maybe assign `frequency[i]` to a variable called something like currentFrequency, to make the code more understandable.

2021-08-13 01:49 UTC, closed without merging